name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure buildozer.spec
      run: |
        sed -i 's/kivymd==1.2.0/kivymd/g' buildozer.spec
        sed -i 's/kivy==2.3.0/kivy/g' buildozer.spec
        sed -i 's/android.api = .*/android.api = 33/g' buildozer.spec
        sed -i 's/android.minapi = .*/android.minapi = 21/g' buildozer.spec
        sed -i 's/android.ndk = .*/android.ndk = 25b/g' buildozer.spec

    - name: Build with Buildozer Action
      uses: ArtemShedko/action-buildozer@v1
      with:
        command: buildozer -v android debug
        subfolder: .

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: bin/*.apk
